### ISSUE TITLE
training

### ISSUE THREAD

**Issue by materialvision** [korneelvdbroek/mp3net#3]
Sooo.... sorry to bother you again but I have managed to preprocess a tfrecord but stuck with an error when trying the launcher.py to train. Any hint for the right parameters to enter? I am currently trying in colab and this fails after the shuffle sequence. 

`Traceback (most recent call last):
  File "launcher.py", line 192, in <module>
    execute(args)
  File "launcher.py", line 112, in execute
    model_trainer.progressive_training()
  File "/content/drive/MyDrive/mp3net/model/progressivetrainer.py", line 70, in progressive_training
    model_weights = model_driver.training_loop(data_files)
  File "/content/drive/MyDrive/mp3net/model/modeldriver.py", line 185, in training_loop
    step = self.train_step(reals_batch_per_replica)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3990, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /content/drive/MyDrive/mp3net/model/modeldriver.py:219 train_step  *
        step_per_replica = self.strategy.run(self.train_step_per_replica_gan, args=(reals,))
    /content/drive/MyDrive/mp3net/model/modeldriver.py:248 train_step_per_replica_gan  *
        if self.discriminator_optimizer.iterations % self.args.n_discr == 0:
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/variables.py:1076 _run_op
        return tensor_oper(a.value(), *args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/math_ops.py:1367 binary_op_wrapper
        return func(x, y, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_math_ops.py:3874 floor_mod
        "FloorMod", x=x, y=y, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py:540 _apply_op_helper
        (input_name, err))

    ValueError: Tried to convert 'y' to a tensor and failed. Error: None values not supported.`

**Comment by korneelvdbroek** [comment]
If I read your error message correctly, the issue is that `n_discr = None`, which is indeed not supported.

I tend to have most success putting `n_discr = 15` for the first ~10,000 iterations (low batch size). Once the loss function of the discriminator is reliably negative, and the loss for the generator positive, then you can switch to  `n_discr = 2`
